In [2]:
#to import numpy, we use this line, and (as np) is used to create an abbreviation of numpy so that in 
#code we just right the short form of the library and not the complete name 
import numpy as np


In [4]:

# Creating a Scalar in Numpy
#In NumPy, a scalar just means a single value (not an array). 
#A NumPy scalar is created when you wrap a single value inside np.array() without brackets.
#It is 0-dimensional, meaning it has no axes:

sc = np.array(25)
print(sc) # this will return only 25 without array brackets[] 


25


In [52]:
# Ndim is used to check Dimention or Degree of the array
print(sc.ndim) # this will return 0 because scaler has 0 dimensions

0


In [28]:

# Creating a Scalar in Numpy
#In NumPy, a scalar just means a single value (not an array). 
#A NumPy scalar is created when you wrap a single value inside np.array() without brackets.
#It is 0-dimensional, meaning it has no axes:

sc = np.array(25)
print(sc) # this will return only 25 without array brackets[] 
print(sc.ndim) # this will return 0 because scaler has 0 dimensions

25
0


In [29]:


# this is to create an empty numpy array 
arr = np.array([])


In [30]:

#Creating a data array, with some values 
arr2 = np.array([1,2,3,4,5])

# type function will return <class 'numpy.ndarray'> because this is an object of type numpy. ndarray, where nd stands for n n-dimensional
# and n can be any integer, for eg, 1D, 2D, 3D, etc. 
print(type(arr))

<class 'numpy.ndarray'>


In [39]:
# 1-D Arrays
# An array that has 0-D arrays as its elements is called a uni-dimensional or 1-D array.
arr4 = np.array([1,2,3,4,5])
print(arr4)                     # this will return [1 2 3 4 5]
print(type(arr4))               # this will return <class 'numpy.ndarray'>
print(arr4.ndim)                # this will return 1

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [48]:
# 2-D Arrays
# An array that has 1-D arrays as its elements is called a 2-D array.
arr5 = np.array([[1,1,1],[-1,-1,-1]])
print(arr5)                     # this will return [[ 1  1  1]
                                #                   [-1 -1 -1]]
print(type(arr5))               # this will return <class 'numpy.ndarray'>
print(arr5.ndim)                # this will return 2


# we can also use a 1D array to create a 2D Array
arr6 = np.array([arr4,arr4])
arr6                            # this will return array([[1, 2, 3, 4, 5],
                                #                        [1, 2, 3, 4, 5]])



[[ 1  1  1]
 [-1 -1 -1]]
<class 'numpy.ndarray'>
2


array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [53]:
# 3-D arrays
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.


arr7 = np.array([[[1,2],[1,2]],[[3,4],[3,4]]])
arr7
print(arr7.ndim)

3


In [61]:
# Creating an Array Using ndmin
arr8 = np.array([1,2,3],ndmin=5)
print(arr8)

[[[[[1 2 3]]]]]


In [ ]:
# Indexing an Array

arr9 = np.array([12,23,4,3,2,34])
print(arr9)
print(arr9[0]) # this will return the 0th position element of the Array, which is 12 in the above array 
print(arr9[5] ) # this will return the 5th position element of the  Array, which is 34 in the above array
print(arr9[-5]) # this will return the 5th position, that means 5th element from the end, which is 23 in the above array 


# Indexing in 2D Array
arr10 = np.array([[1,2,3],[-1,-2,-3]])
print(arr10[0,0]) # This will return 0th element of 0th array , which is 1 in the above arr10 array
print(arr10[0,1]) # This will return 1th element of 0th array , which is 2 in the above arr10 array
print(arr10[1,2]) # This will return 2th element of 1th array , which is -3 in the above arr10 array

# Indexing in 3D Array
arr11 = np.array([[[1,2,3],[1,2,-4]],[[3,4,1],[3,4,0]]])
print(arr11[0,1,2]) # This returns the 2nd element (index 2) of the 1st 1D array (index 1) inside the 0th 2D array (index 0), which is -4.
print(arr11[0,0,0]) #This returns the 0th element of the 0th 1D array inside the 0th 2D array, which is 1.
print(arr11[1,1,1]) # This returns the 1st element of the 1st 1D array inside the 1st 2D array, which is 4.
print(arr11[1,1,2]) # This returns the 2nd element of the 1st 1D array inside the 1st 2D array, which is 0.


In [3]:
# Slicing an Array - Array slicing means extracting a portion of an array using indexes.

# The general syntax is:array[start:stop:step]

# start → index where the slice begins (inclusive). Default = 0

# stop → index where the slice ends (exclusive). Default = length of array

# step → interval between elements. Default = 1

#There are 2 types of Array -

# 1. 1D Array 

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[1:4])    # [20 30 40]
print(arr[:3])     # [10 20 30]
print(arr[2:])     # [30 40 50 60]
print(arr[::2])    # [10 30 50]
print(arr[::-1])   # [60 50 40 30 20 10] (reversed)


# 2. 2D Array 

arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [10,11,12]])

print(arr2[1:3, :])     # Rows 1-2, all columns
# [[4 5 6]
#  [7 8 9]]

print(arr2[:, 0:2])     # All rows, first 2 columns
# [[ 1  2]
#  [ 4  5]
#  [ 7  8]
#  [10 11]]

print(arr2[::2, 1:])    # Every 2nd row, columns 1 onward
# [[ 2  3]
#  [11 12]]

# 3. 3D Array 
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                 [[10,11,12],[13,14,15],[16,17,18]],
                 [[19,20,21],[22,23,24],[25,26,27]]])

print(arr3[0])        # First 2D matrix
print(arr3[:, 1, :])  # Row=1 from all matrices
print(arr3[:, :, 0])  # First column from all matrices
print(arr3[1:, 1:, 1:]) # Slice depth=1→end, row=1→end, col=1→end


[20 30 40]
[10 20 30]
[30 40 50 60]
[10 30 50]
[60 50 40 30 20 10]
[[4 5 6]
 [7 8 9]]
[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]
[[2 3]
 [8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [13 14 15]
 [22 23 24]]
[[ 1  4  7]
 [10 13 16]
 [19 22 25]]
[[[14 15]
  [17 18]]

 [[23 24]
  [26 27]]]


In [ ]:
                                                               # Array Manipulation


In [16]:


# Array Arrange

# this method is used to create a New Array With Given Start, Stop, & Step Values 
# this will work similarly to python range()function used in a for loop  , 
#where we provide start point, end point, and increment or decrement of the loop.


# np.arange([start, ]stop, [step], dtype=None)
arr1 = np.arange(5)   # this will create an array([0, 1, 2, 3, 4]) starting from 0 and ending at 4. 
print(arr1)

arr2 = np.arange(5,10) # this will create an array [5 6 7 8 9] starting from 5 and ending at 9 
print(arr2)

arr3 = np.arange(5,100,10) # this will create an array [ 5 15 25 35 45 55 65 75 85 95] starting 
                           # from 5 and ending at 95 that have an increment of 10  
print(arr3)

arr4 = np.arange(10,5,-1) # this will create a Reversed Array [10  9  8  7  6]  starting from 10 and ending at 6
                          # that has a decrement of -1 
print(arr4)


# Floating point increment
arr5 = np.arange(1,10,0.5) # this will create an array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
                           #                               7.5, 8. , 8.5, 9. , 9.5])  
                           # starting from 1 and ending at 9.5 that have an increment of 0.5 
print(arr5)

arr6 = np.arange(1,10,dtype=float)  # this will create a array with custom dtype float 
print(arr6)




[0 1 2 3 4]
[5 6 7 8 9]
[ 5 15 25 35 45 55 65 75 85 95]
[10  9  8  7  6]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [38]:
# Array Linspace ( Linear Space )
# This Numpy Method is used to create an array with a  given starting point, 
# ending point and total number of elements evenly distributed in that given range.  
 

arr1 = np.linspace(0,10,5) # this will return an array [ 0.   2.5  5.   7.5 10. ] with starting point 0, ending point 10, and 
                           #  having exactly 5 evenly distributed elements
print(arr1)

# In LinSpace, we can not pass a floating point as the 3rd argument, which will only accept integers 

#arr1 = np.linspace(0,10,2.5) so this will give a error 


arr2 = np.linspace(0,10,5,endpoint=False)  # this will return an array [0. 2. 4. 6. 8.] with starting point 0, ending point excluding(10) 
                                           # exactly 5 evenly distributed elements 
print(arr2)





[ 0.   2.5  5.   7.5 10. ]
[0. 2. 4. 6. 8.]


In [88]:
# Numpy Reshape Method

# The reshape method in NumPy is used to reshape a 1-dimensional array to a multidimensional array.

arr1 = np.arange(15)
print(arr1)

# 1D to 2D array Reshape
arr2 = arr1.reshape(5,3) # This Will Return a Reshaped Array [[ 0  1  2] ,[ 3  4  5] ,[ 6  7  8] ,[ 9 10 11] ,[12 13 14]] in 5X3 order 
                         # Having 5 arrays of 3 Elements each

print(arr2)



#arr2 = arr1.reshape(2,2) # This will return an Error, because we can not reshape an array of 15 elements intoa  2X2  

# 1D to 3D Array 

arr3 = np.arange(20)
arr4 = arr3.reshape(5,2,2) # This Will Create a 3D  Array , that have
                           #  a. 5 2D array b. each 2D array have 4 rows c . and each row will have 1 column 
print(arr4)
print(arr4.ndim)


arr5 = arr3.reshape(2,5,2) # This Will Create a 3D  Array , that have 
                           #  a. 2 2D array b. each 2D array have 5 rows c . and each row will have 2 column
print(arr5)




# Auto Arrange Columns 
arr6 = arr3.reshape(5,-1) # this -1 on the place of columns will allow numpy to auto calculate column number
print(arr6)


arr7 = arr3.reshape(-1,5)  # this -1 on the place of row number will allow numpy to auto calculate row number 
print(arr7)




# Flatten a Array With the Help of Reshape Function
arr = np.array([[12,3],[23,4],[34,35],[46,4]])
print(arr)

arr8 = arr.reshape(-1) # this -1 allow Numpy to Flatten the array and will return a 1D array
print(arr8)

arr9 = arr.reshape(1,-1)  # this will create a row vector , when there is 1 row and n number columns 
print(arr9)

arr10 = arr.reshape(-1,1) # this will create a column vector , when there is 1 column and n number of rows . 
print(arr10)



#order='C' (row-major)
arr = np.arange(20) # 
print(arr)   # [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
arr11 = arr.reshape(5,4,order="C")  # this will return a array that will start filling by row 
                                    # [[ 0  1  2  3]
                                      #  [ 4  5  6  7]
                                       #  [ 8  9 10 11]
                                       # [12 13 14 15]
                                       #  [16 17 18 19]]

print(arr11)


#order='F' (column-major)
arr12 = arr.reshape(5,4,order="F")  # this will return a array that will start filling up by column
                                    # [[ 0  5 10 15]
                                    #  [ 1  6 11 16]
                                    #  [ 2  7 12 17]
                                    #  [ 3  8 13 18]
#  [ 4  9 14 19]]
print(arr12)









[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]
3
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[12  3]
 [23  4]
 [34 35]
 [46  4]]
[12  3 23  4 34 35 46  4]
[[12  3 23  4 34 35 46  4]]
[[12]
 [ 3]
 [23]
 [ 4]
 [34]
 [35]
 [46]
 [ 4]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
