In [10]:
#to import numpy, we use this line, and (as np) is used to create an abbreviation of numpy so that in 
#code we just right the short form of the library and not the complete name 
import numpy as np


In [28]:

# Creating a Scalar in Numpy
#In NumPy, a scalar just means a single value (not an array). 
#A NumPy scalar is created when you wrap a single value inside np.array() without brackets.
#It is 0-dimensional, meaning it has no axes:

sc = np.array(25)
print(sc) # this will return only 25 without array brackets[] 


25
0


In [52]:
# Ndim is used to check Dimention or Degree of the array
print(sc.ndim) # this will return 0 because scaler has 0 dimensions

0


In [28]:

# Creating a Scalar in Numpy
#In NumPy, a scalar just means a single value (not an array). 
#A NumPy scalar is created when you wrap a single value inside np.array() without brackets.
#It is 0-dimensional, meaning it has no axes:

sc = np.array(25)
print(sc) # this will return only 25 without array brackets[] 
print(sc.ndim) # this will return 0 because scaler has 0 dimensions

25
0


In [29]:


# this is to create an empty numpy array 
arr = np.array([])


In [30]:

#Creating a data array, with some values 
arr2 = np.array([1,2,3,4,5])

# type function will return <class 'numpy.ndarray'> because this is an object of type numpy. ndarray, where nd stands for n n-dimensional
# and n can be any integer, for eg, 1D, 2D, 3D, etc. 
print(type(arr))

<class 'numpy.ndarray'>


In [39]:
# 1-D Arrays
# An array that has 0-D arrays as its elements is called a uni-dimensional or 1-D array.
arr4 = np.array([1,2,3,4,5])
print(arr4)                     # this will return [1 2 3 4 5]
print(type(arr4))               # this will return <class 'numpy.ndarray'>
print(arr4.ndim)                # this will return 1

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [48]:
# 2-D Arrays
# An array that has 1-D arrays as its elements is called a 2-D array.
arr5 = np.array([[1,1,1],[-1,-1,-1]])
print(arr5)                     # this will return [[ 1  1  1]
                                #                   [-1 -1 -1]]
print(type(arr5))               # this will return <class 'numpy.ndarray'>
print(arr5.ndim)                # this will return 2


# we can also use a 1D array to create a 2D Array
arr6 = np.array([arr4,arr4])
arr6                            # this will return array([[1, 2, 3, 4, 5],
                                #                        [1, 2, 3, 4, 5]])



[[ 1  1  1]
 [-1 -1 -1]]
<class 'numpy.ndarray'>
2


array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [53]:
# 3-D arrays
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.


arr7 = np.array([[[1,2],[1,2]],[[3,4],[3,4]]])
arr7
print(arr7.ndim)

3


In [61]:
# Creating an Array Using ndmin
arr8 = np.array([1,2,3],ndmin=5)
print(arr8)

[[[[[1 2 3]]]]]


In [98]:
# Indexing an Array

arr9 = np.array([12,23,4,3,2,34])
print(arr9)
print(arr9[0]) # this will return the 0th position element of the Array, which is 12 in the above array 
print(arr9[5] ) # this will return the 5th position element of the  Array, which is 34 in the above array
print(arr9[-5]) # this will return the 5th position, that means 5th element from the end, which is 23 in the above array 


# Indexing in 2D Array
arr10 = np.array([[1,2,3],[-1,-2,-3]])
print(arr10[0,0]) # This will return 0th element of 0th array , which is 1 in the above arr10 array
print(arr10[0,1]) # This will return 1th element of 0th array , which is 2 in the above arr10 array
print(arr10[1,2]) # This will return 2th element of 1th array , which is -3 in the above arr10 array

# Indexing in 3D Array
arr11 = np.array([[[1,2,3],[1,2,-4]],[[3,4,1],[3,4,0]]])
print(arr11[0,1,2]) # This returns the 2nd element (index 2) of the 1st 1D array (index 1) inside the 0th 2D array (index 0), which is -4.
print(arr11[0,0,0]) #This returns the 0th element of the 0th 1D array inside the 0th 2D array, which is 1.
print(arr11[1,1,1]) # This returns the 1st element of the 1st 1D array inside the 1st 2D array, which is 4.
print(arr11[1,1,2]) # This returns the 2nd element of the 1st 1D array inside the 1st 2D array, which is 0.


[12 23  4  3  2 34]
12
34
23
1
2
-3
-4
1
4
0
